version: 0.2

run-as: root
        
phases:
  install:
    run-as: root
    on-failure: ABORT 
    commands:
      - yum update -y
      - yum install docker -y


  pre_build:
    run-as: root
    on-failure: ABORT
    commands:
      - docker pull httpd
      - docker images
      - echo "image pull completed"

  build:
    run-as: root
    on-failure: ABORT 
    commands:
      - docker build -t simpledevops:latest .
    finally:
      - echo "Completed Docker image build"
